# -*- coding: utf-8 -*-
"""PMG Coding Challenge.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10x5RkdmNWlbqxo3Zd5uw_wYQaPiFAFwz
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import os
# %cd ../fixtures/

master_df = pd.DataFrame()
accumulator_df2 = pd.DataFrame()
PATH = os.path.join(os.getcwd())

for file in os.listdir(PATH):
  if file.endswith('.csv'):
    accumulator_df = pd.read_csv(file)
    accumulator_df = accumulator_df.assign(filename = file)
    master_df = master_df.append(accumulator_df)

master_df

os.getcwd()